version: '3'

services:
  # Laravel Application
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-app:/var/www/html
    networks:
      - app-network
      - db

  # MySQL Database
  db:
    platform: linux/x86_64
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news-app
      MYSQL_PASSWORD: password
    networks:
      - db

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db   

  # React Frontend (Assuming you have a separate directory for React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-app
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  db:

  # Additional services can be added here if needed
